# Compiler to use
CC = g++

LinkedStack:
	$(CC) LinkedStack.cpp -o LinkedStack #creates executable file
	$(CC) -Wall -c LinkedStack.cpp #creates object file using -c

clean:
	rm LinkedStack LinkedStack.o
